---
title: "Bases de datos del Barómetro de las Américas"
output:
  html_document:
    toc: true
    toc_float: true
    collapsed: false
    number_sections: false
    toc_depth: 1
    #code_folding: hide
    theme: flatly
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(message=FALSE,warning=FALSE, cache=TRUE)
```

```{css color, echo=FALSE}
.columns {display: flex;}
h1 {color: #3366CC;}
```

# Introducción

Los datos que vamos a usar a lo largo de todos estos temas corresponden al proyecto del Barómetro de las Américas de [LAPOP Lab](https://www.vanderbilt.edu/lapop/). Como centro de excelencia en investigación por encuestas, LAPOP Lab usa enfoques y métodos innovadores con los “estándares más altos” para llevar a cabo encuestas nacionales; conducir estudios de evaluación de impacto, y producir reportes acerca de las actitudes, evaluaciones y experiencias de los individuos. El Barómetro de las Américas es la única encuesta comparativa y científicamente rigurosa que cubre 34 naciones incluyendo Norte, Centro y Sur América, así como también, un significativo número de países en el Caribe. Cada año publica docenas de estudios académicos de alta calidad y artículos de relevancia para la elaboración de políticas públicas.

El Barómetro de las Américas del 2018/19 representa la octava ronda de este proyecto. El cuestionario contiene un módulo común que permite evaluar hasta qué punto los ciudadanos apoyan los valores democráticos, perciben que hay suficiente provisión de libertades básicas, cómo experimentan el Estado de Derecho, participan en la vida política, apoyan su sistema de gobierno, usan las redes sociales, entre otros.

La base de datos y los reportes del proyecto son públicos y se encuentran disponibles de forma gratuita en la [página web del proyecto](www.lapopsurveys.org).

Estos datos deben citarse de la siguiente manera:
Fuente: Barómetro de las Américas por el Proyecto de Opinión Pública de América Latina (LAPOP), wwww.LapopSurveys.org.

# Para descargar los datos

Pueden descargar los datos de manera libre  [aquí](http://datasets.americasbarometer.org/database/login.php)
En este enlace, se pueden registrar o entrar como "Free User". En el buscador, se puede ingresar el texto "2018". Ahí se tendrá acceso a la base de datos completa "2018 LAPOP AmericasBarometer Merge_v1.0_W.dta en versión para STATA. Se descarga la base de datos en formato zip, la que se descomprime en formato .dta.
Una vez descargada y guardada en el directorio de trabajo, se puede leer la base de datos en STATA como un objeto dataframe en R.
A lo largo de los temas, se usarán bases de datos recortadas de la ronda 2018/19. Estas base de datos se encuentran alojadas en el repositorio "materials_edu" de la cuenta de LAPOP en [GitHub](https://github.com/lapop-central/materials_edu).
En los módulos temáticos veremos como importar estas bases de datos de GitHub mediante la librería `rio` y el comando `import`.
