<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />




<title>Estadística descriptiva usando el Barómetro de las Américas (1)</title>

<script src="site_libs/header-attrs-2.7/header-attrs.js"></script>
<script src="site_libs/jquery-1.11.3/jquery.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/bootstrap.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<style>h1 {font-size: 34px;}
       h1.title {font-size: 38px;}
       h2 {font-size: 30px;}
       h3 {font-size: 24px;}
       h4 {font-size: 18px;}
       h5 {font-size: 16px;}
       h6 {font-size: 12px;}
       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}
       pre:not([class]) { background-color: white }</style>
<script src="site_libs/jqueryui-1.11.4/jquery-ui.min.js"></script>
<link href="site_libs/tocify-1.9.1/jquery.tocify.css" rel="stylesheet" />
<script src="site_libs/tocify-1.9.1/jquery.tocify.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<link href="site_libs/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>

<style type="text/css">code{white-space: pre;}</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>








<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
pre code {
  padding: 0;
}
</style>


<style type="text/css">
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #adb5bd;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script type="text/javascript">
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark it active
  menuAnchor.tab('show');

  // if it's got a parent navbar menu mark it active as well
  menuAnchor.closest('li.dropdown').addClass('active');

  // Navbar adjustments
  var navHeight = $(".navbar").first().height() + 15;
  var style = document.createElement('style');
  var pt = "padding-top: " + navHeight + "px; ";
  var mt = "margin-top: -" + navHeight + "px; ";
  var css = "";
  // offset scroll position for anchor links (for fixed navbar)
  for (var i = 1; i <= 6; i++) {
    css += ".section h" + i + "{ " + pt + mt + "}\n";
  }
  style.innerHTML = "body {" + pt + "padding-bottom: 40px; }\n" + css;
  document.head.appendChild(style);
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "&#xe258;";
  border: none;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->



<style type="text/css">

#TOC {
  margin: 25px 0px 20px 0px;
}
@media (max-width: 768px) {
#TOC {
  position: relative;
  width: 100%;
}
}

@media print {
.toc-content {
  /* see https://github.com/w3c/csswg-drafts/issues/4434 */
  float: right;
}
}

.toc-content {
  padding-left: 30px;
  padding-right: 40px;
}

div.main-container {
  max-width: 1200px;
}

div.tocify {
  width: 20%;
  max-width: 260px;
  max-height: 85%;
}

@media (min-width: 768px) and (max-width: 991px) {
  div.tocify {
    width: 25%;
  }
}

@media (max-width: 767px) {
  div.tocify {
    width: 100%;
    max-width: none;
  }
}

.tocify ul, .tocify li {
  line-height: 20px;
}

.tocify-subheader .tocify-item {
  font-size: 0.90em;
}

.tocify .list-group-item {
  border-radius: 0px;
}


</style>



</head>

<body>


<div class="container-fluid main-container">


<!-- setup 3col/9col grid for toc_float and main content  -->
<div class="row">
<div class="col-sm-12 col-md-4 col-lg-3">
<div id="TOC" class="tocify">
</div>
</div>

<div class="toc-content col-sm-12 col-md-8 col-lg-9">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">LAPOP_edu</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="index.html">Home</a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Básico
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="instalando.html">Instalando R y RStudio</a>
    </li>
    <li>
      <a href="bases.html">Bases de datos</a>
    </li>
  </ul>
</li>
<li>
  <a href="Manipulacion.html">Manejo de datos</a>
</li>
<li>
  <a href="Expansion.html">Factor de expansión</a>
</li>
<li>
  <a href="Descriptivos.html">Descriptivos variables nominales</a>
</li>
<li>
  <a href="Links.html">Contacto</a>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div id="header">



<h1 class="title toc-ignore">Estadística descriptiva usando el Barómetro de las Américas (1)</h1>

</div>


<style type="text/css">
.columns {display: flex;}
h1 {color: #3366CC;}
</style>
<div id="introducción" class="section level1">
<h1>Introducción</h1>
<p>En este documento empezaremos con los aspectos básicos de cómo usar la base de datos del Barómetro de las Américas de LAPOP para fines estadísticos. En primer lugar, veremos aspectos básicos de cómo describir una variable mediante una tabla de distribución de frecuencias y cómo graficar esa variable. Para eso, vamos a usar el último informe regional “El pulso de la democracia”, disponible <a href="https://www.vanderbilt.edu/lapop/ab2018/2018-19_AmericasBarometer_Regional_Report_Spanish_W_03.27.20.pdf">aquí</a>, donde se presentan los principales hallazgos de la ronda 2018/19 del Barómetro de las Américas. Una de las secciones de este informe, reporta los datos sobre redes sociales y actitudes políticas. En esta sección, se presentan datos sobre el uso de internet y el uso de redes sociales, en general y por país. Con los datos del Barómetro de las Américas se puede saber el % de hogares con acceso a celulares, con acceso a internet, así como el % de personas que usa Whatsapp, Facebook o Twitter. En este documento vamos a reproducir estos resultados.</p>
</div>
<div id="sobre-la-base-de-datos" class="section level1">
<h1>Sobre la base de datos</h1>
<p>Los datos que vamos a usar deben citarse de la siguiente manera: Fuente: Barómetro de las Américas por el Proyecto de Opinión Pública de América Latina (LAPOP), wwww.LapopSurveys.org. Pueden descargar los datos de manera libre <a href="http://datasets.americasbarometer.org/database/login.php">aquí</a> En este enlace, se pueden registrar o entrar como “Free User”. En el buscador, se puede ingresar el texto “2018”. Ahí se tendrá acceso a la base de datos completa “2018 LAPOP AmericasBarometer Merge_v1.0_W.dta en versión para STATA. Se descarga la base de datos en formato zip, la que se descomprime en formato .dta. Una vez descargada y guardada en el directorio de trabajo, se tiene que leer la base de datos como un objeto dataframe en R. En este documento se carga una base de datos recortada. Esta base de datos se encuentra alojada en el repositorio”materials_edu" de la cuenta de LAPOP en GitHub. Mediante la librería <code>rio</code> y el comando <code>import</code> se puede importar esta base de datos desde este repositorio. Además, se seleccionan los datos de países con códigos menores o iguales a 35, es decir, elimina las observaciones de Estados Unidos y Canadá.</p>
<pre class="r"><code>library(rio)
lapop18 &lt;- import(&quot;https://raw.github.com/lapop-central/materials_edu/main/LAPOP_AB_Merge_2018_v1.0.sav&quot;)
lapop18 &lt;- subset(lapop18, pais&lt;=35)</code></pre>
<p>Las variables con las que se trabajará son: SMEDIA1. ¿Tiene usted cuenta de Facebook?; SMEDIA4. ¿Tiene usted cuenta de Twitter?; SMEDIA7. ¿Tiene usted cuenta de Whatsapp?. Estas preguntas tienen como opciones:</p>
<ol style="list-style-type: decimal">
<li>Sí</li>
<li>No</li>
</ol>
<p>Al momento de leer la base de datos en R, este programa importa las variables como “dbl+lbl” o como “num”, que la mayoría de funciones en R trata como numéricas. Estas variables se tienen que convertir a variables de tipo “factor”, pues son variables categóricas, las que guardamos en una nueva variable.</p>
<pre class="r"><code>lapop18$smedia1r = as.factor(lapop18$smedia1)
lapop18$smedia4r = as.factor(lapop18$smedia4)
lapop18$smedia7r = as.factor(lapop18$smedia7)</code></pre>
<p>Y luego se tienen que etiquetar.</p>
<pre class="r"><code>levels(lapop18$smedia1r) &lt;- c(&quot;Sí&quot;, &quot;No&quot;)
levels(lapop18$smedia4r) &lt;- c(&quot;Sí&quot;, &quot;No&quot;)
levels(lapop18$smedia7r) &lt;- c(&quot;Sí&quot;, &quot;No&quot;)</code></pre>
</div>
<div id="calcular-las-variables-de-usuarios-de-redes-sociales" class="section level1">
<h1>Calcular las variables de usuarios de redes sociales</h1>
<p>Como vimos en un documento anterior, se puede calcular nuevas variables con valores condicionales de otras variables usando el comando <code>ifelse</code>. De esta manera, se crea la variable de usuarios de redes sociales.</p>
<pre class="r"><code>lapop18$fb_user &lt;- ifelse(lapop18$smedia1==1 &amp; lapop18$smedia2&lt;=4, 1, 0)
lapop18$tw_user &lt;- ifelse(lapop18$smedia4==1 &amp; lapop18$smedia5&lt;=4, 1, 0)
lapop18$wa_user &lt;- ifelse(lapop18$smedia7==1 &amp; lapop18$smedia8&lt;=4, 1, 0)</code></pre>
</div>
<div id="describir-las-variables" class="section level1">
<h1>Describir las variables</h1>
<p>Con las variables listas, ahora procedemos a hacer las tablas generales con el comando <code>table</code>. Se puede notar el uso de <code>#</code> como forma de hacer anotaciones, que no son código en R.</p>
<pre class="r"><code>table(lapop18$smedia1r) #Facebook</code></pre>
<pre><code>## 
##    Sí    No 
## 15389 11573</code></pre>
<pre class="r"><code>table(lapop18$smedia4r) #Twitter</code></pre>
<pre><code>## 
##    Sí    No 
##  2363 24558</code></pre>
<pre class="r"><code>table(lapop18$smedia7r) #Whatsapp</code></pre>
<pre><code>## 
##    Sí    No 
## 17446  9569</code></pre>
<p>Este comando <code>table</code> nos brinda las frecuencias absolutas (número de observaciones) por cada categoría de la variable (en este caso Sí y No). Para obtener las frecuencias relativas, usaremos el comando <code>prop.table</code>, donde se anida el comando anterior <code>table</code>.</p>
<pre class="r"><code>prop.table(table(lapop18$smedia1r))</code></pre>
<pre><code>## 
##        Sí        No 
## 0.5707663 0.4292337</code></pre>
<pre class="r"><code>prop.table(table(lapop18$smedia4r))</code></pre>
<pre><code>## 
##         Sí         No 
## 0.08777534 0.91222466</code></pre>
<pre class="r"><code>prop.table(table(lapop18$smedia7r))</code></pre>
<pre><code>## 
##        Sí        No 
## 0.6457894 0.3542106</code></pre>
<p>Sin embargo, el comando <code>prop.table</code> nos devuelve demasiados decimales. Para redondear esta cifra usamos el comando <code>round</code>, que nos permite especificar el número de decimales que se quiere mostrar. Tanto el comando <code>table</code>, como <code>prop.table</code> se anidan dentro de este nuevo comando. En este caso se ha usado 3 decimales, para cuando se multiplique por 100, quede en forma de porcentaje con 1 decimal.</p>
<pre class="r"><code>round(prop.table(table(lapop18$smedia1r)), 3)*100</code></pre>
<pre><code>## 
##   Sí   No 
## 57.1 42.9</code></pre>
<pre class="r"><code>round(prop.table(table(lapop18$smedia4r)), 3)*100</code></pre>
<pre><code>## 
##   Sí   No 
##  8.8 91.2</code></pre>
<pre class="r"><code>round(prop.table(table(lapop18$smedia7r)), 3)*100</code></pre>
<pre><code>## 
##   Sí   No 
## 64.6 35.4</code></pre>
<p>No es práctico presentar 3 tablas cuando las variables tienen las mismas categorías de respuesta. Es mejor construir una sola tabla. Se puede guardar las tablas parciales en nuevos objetos con el operador <code>&lt;-</code> y luego unirlas con el comando <code>rbind</code> en un nuevo dataframe “tabla”, de tal manera que las respuestas a cada red social aparezcan en filas.</p>
<pre class="r"><code>Facebook &lt;- round(prop.table(table(lapop18$smedia1r)), 3)*100
Twitter &lt;- round(prop.table(table(lapop18$smedia4r)), 3)*100
Whatsapp &lt;- round(prop.table(table(lapop18$smedia7r)), 3)*100
tabla &lt;- as.data.frame(rbind(Facebook, Twitter, Whatsapp))
tabla</code></pre>
<pre><code>##            Sí   No
## Facebook 57.1 42.9
## Twitter   8.8 91.2
## Whatsapp 64.6 35.4</code></pre>
<p>Para tener una mejor presentación de la tabla, se puede usar el comando <code>kable</code> del paquete <code>knitr</code>.</p>
<pre class="r"><code>library(knitr)
knitr::kable(tabla, format=&quot;markdown&quot;)</code></pre>
<table>
<thead>
<tr class="header">
<th align="left"></th>
<th align="right">Sí</th>
<th align="right">No</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Facebook</td>
<td align="right">57.1</td>
<td align="right">42.9</td>
</tr>
<tr class="even">
<td align="left">Twitter</td>
<td align="right">8.8</td>
<td align="right">91.2</td>
</tr>
<tr class="odd">
<td align="left">Whatsapp</td>
<td align="right">64.6</td>
<td align="right">35.4</td>
</tr>
</tbody>
</table>
</div>
<div id="describir-las-variables-tomando-en-cuenta-en-factor-de-expansión" class="section level1">
<h1>Describir las variables tomando en cuenta en factor de expansión</h1>
<p>Los resultados presentados no son exactamente iguales a los del reporte pues LAPOP incluye el efecto del diseño muestral en sus cálculos. Según esta sintaxis, se encuentra que el 57.1% de entrevistados reporta ser usuario de Facebook, cuando en el reporte aparece 56.2%. Lo mismo con Twitter, que aquí se calcula en 8.8% y en el reporte 7.9%; y con Whatsapp que aquí aparece con 64.6% y en el reporte con 64.4%. Como se indicó en el documento sobre el uso de los factores de expansión usando los datos del Barómetro de las Américas (disponible <a href="https://rpubs.com/arturo_maldonado/728626">aquí</a>), hay varias maneras de reproducir los resultados incorporando el efecto de diseño. Para reproducir los datos del reporte exactamente se tiene que incluir este efecto de diseño en R mediante el paquete <code>survey</code>. Como esta es una introducción a la estadística descriptiva, no se ha hecho, pero más adelante se incluirá en los cálculos el efecto de diseño. En este documento se puede usar el comando <code>freq</code> que permite la inclusión de una variable de factor de expansión, como “weight1500”. Se incluye la especificación <code>plot=F</code> para no producir los gráficos de barras.</p>
<pre class="r"><code>library(descr)
descr::freq(lapop18$fb_user, lapop18$weight1500, plot = F)</code></pre>
<pre><code>## lapop18$fb_user 
##       Frequency Percent Valid Percent
## 0         11337  41.988         43.77
## 1         14564  53.939         56.23
## NA&#39;s       1100   4.073              
## Total     27000 100.000        100.00</code></pre>
<pre class="r"><code>descr::freq(lapop18$tw_user, lapop18$weight1500, plot = F)</code></pre>
<pre><code>## lapop18$tw_user 
##       Frequency Percent Valid Percent
## 0         23819  88.220        92.023
## 1          2065   7.647         7.977
## NA&#39;s       1116   4.133              
## Total     27000 100.000       100.000</code></pre>
<pre class="r"><code>descr::freq(lapop18$wa_user, lapop18$weight1500, plot = F)</code></pre>
<pre><code>## lapop18$wa_user 
##       Frequency Percent Valid Percent
## 0          9252  34.266         35.63
## 1         16714  61.903         64.37
## NA&#39;s       1035   3.832              
## Total     27000 100.000        100.00</code></pre>
</div>
<div id="graficar-las-variables" class="section level1">
<h1>Graficar las variables</h1>
<p>En la página 54 del reporte se observa que se reportan estos datos en forma gráfica, mediante un gráfico de sectores. Se puede reproducir ese gráfico usando el comando <code>pie</code> que es parte de la sintaxis básica de R. Dentro de este comando se puede anidar el comando <code>table</code> para graficar estos valores.</p>
<pre class="r"><code>pie(table(lapop18$smedia1r))</code></pre>
<p><img src="Descriptivos_files/figure-html/pie-1.png" width="672" /></p>
<p>También se podría pensar en un gráfico de barras. Usando los comandos básicos de R, se puede usar el comando <code>barplot</code>.</p>
<pre class="r"><code>barplot(prop.table(table(lapop18$smedia1r)))</code></pre>
<p><img src="Descriptivos_files/figure-html/barras%20simple-1.png" width="672" /></p>
<p>Para tener más opciones gráficas, podemos usar el paquete <code>ggplot</code> para reproducir el gráfico circular. En este ejemplo, se ha usado el comando <code>subset</code> nuevamente, pero dentro de <code>ggplot</code> para que el comando (internamente) trabaje con la variable pero sin los valores perdidos. La sintaxis <code>!is.na()</code> hace que el comando no incluya los valores perdidos de una variable en los cálculos. Si se hubiera usado <code>data=lapop</code> el gráfico hubiera incluido un gran sector correspondiente a la proporción de NA. Si se hubiera usado <code>!is.na()</code> fuera de <code>ggplot</code> creando una nueva variable, se hubieran eliminado todas las observaciones con valores perdidos, lo que disminuiría el N, afectando futuros cálculos. Luego, la especificación <code>aes</code> sirve para definir la “estética” del gráfico. Generalmente se usa para indicar qué variable se va a graficar y en qué eje (x o y). También se puede usar la especificación <code>fill=</code> para definir los grupos que se van a generar. El comando <code>ggplot</code> trabaja sumando capas. Luego de especificar los datos y los ejes, se tiene que especificar el tipo de gráfico que se quiere realizar. Esto se hace con las geometrías (“geom”). No existe una geometría directa para hacer un gráfico circulas, por lo que se tiene que usar inicialmente un gráfico de barras simple, usando el comando <code>geom_bar()</code>, donde internamente se define el ancho de la barra. Si dejáramos la sintaxis en este punto, se generaria una barra que se dividiría entre los valores de la variable “smedia1r”. Para genera el gráfico circular, se tiene que agregar otro comando <code>coord_polar</code>, que transforma la barra a coordenadas polares, creando un gráfico curcular.</p>
<pre class="r"><code>library(ggplot2) #librería especializada en gráficos
library(scales) #para formatear las etiquetas en porcentajes
ggplot(data=subset(lapop18, !is.na(smedia1r)), aes(x=&quot;&quot;, fill=smedia1r))+
  geom_bar(width=1) +
  coord_polar(&quot;y&quot;, start=0)</code></pre>
<p><img src="Descriptivos_files/figure-html/ggpie-1.png" width="672" /></p>
<p>El gráfico anterior ha partido desde el mismo dataframe “lapop18”, usando los datos de “smedia1r”. Sin embargo, para manipular mejor el gráfico es más fácil crear un nuevo dataframe con los datos agregados (frecuencia y %). Luego se usa ese nuevo dataframe para hacer el pie con <code>ggplot</code>. Un aspecto a resaltar es que en este caso se está usando el pipe <code>%&gt;%</code> de la librería <code>dply</code>, que es una forma (un poco) diferente de escribir códigos en R, de manera concatenada, paso a paso. Una explicación simple de cómo se usa el pipe se puede encontrar <a href="https://psyr.djnavarro.net/prelude-to-data.html#124_the_pipe,_%%">aquí</a>. Lo primero que hay que notar es que se va a crear un nuevo objeto llamado “df”. En este objeto se va a guardar información que viene del dataframe “lapop18”. Se usa el comando <code>subset</code> para eliminar los valores perdidos de “smedia1r” del cálculo de los porcentajes. Luego (<code>%&gt;%</code>), estos datos se van a agrupar por categorías de la variable “smedia1r”. A continuación (<code>%&gt;%</code>), en cada grupo se calcula el total de observaciones con el comando <code>summarise(n = n())</code>. Finalmente (último paso con <code>%&gt;%</code>), con este total por grupos se calcula los porcentajes y se guarda estos porcentajes en una nueva columna “per”. La especificación <code>lab.pos</code> no la explicaremos aquí (aunque sirve para luego ubicar la etiqueta en el gráfico).</p>
<pre class="r"><code>library(dplyr)
df &lt;- subset(lapop18, !is.na(smedia1r)) %&gt;%
      group_by(smedia1r) %&gt;% 
      summarise(n = n()) %&gt;%
      mutate(per=round(n/sum(n), 3)*100, lab.pos=cumsum(per)-0.5*per)
df</code></pre>
<pre><code>## # A tibble: 2 x 4
##   smedia1r     n   per lab.pos
##   &lt;fct&gt;    &lt;int&gt; &lt;dbl&gt;   &lt;dbl&gt;
## 1 Sí       15389  57.1    28.6
## 2 No       11573  42.9    78.6</code></pre>
<p>Con esta sintaxis se crea una tabla donde se tiene el total de observaciones y el porcentaje por cada categoría de la variable “smedia1r”. Una forma más directa de crear los mismos datos es usando la librería <code>janitor</code> y el comando <code>tabyl</code>. En R existen múltiples maneras de llegar a los mismos resultados.</p>
<pre class="r"><code>library(janitor)
subset(lapop18, !is.na(smedia1r)) %&gt;%
  tabyl(smedia1r)</code></pre>
<pre><code>##  smedia1r     n   percent
##        Sí 15389 0.5707663
##        No 11573 0.4292337</code></pre>
<p>Una vez que tenemos la tabla, podemos usarla para trabajar el gráfico circular con <code>ggplot</code>. Nótese que, en este caso, los datos que se usan vienen del dataframe df (no lapop18). Este dataframe tiene una columna llamada “per” con los porcentajes respectivos que se grafican en el eje Y. Igual que en el caso anterior, para hacer el gráfico circular, se parte del gráfico de barras (por eso <code>geom_bar</code>), que luego se pasa a coordenadas polares (por eso <code>coord_polar</code>). Se agrega una capa de texto, con la especificación <code>geom_text</code>. Dentro de esta especificación se determina una “estética” con la etiqueta del dato <code>aes(label=...</code>, donde se junta con el comando <code>paste</code> el dato del porcentaje “per” y el símbolo “%”, con un espacio (<code>sep=...</code>) entre ellos. Se establece el color de la fuente con <code>color=...</code>. Se ajusta a blanco para que contraste con los colores del gráfico circular. Con el comando <code>hjust=...</code> se ajusta la posición horizontal de este texto. El comando <code>ggplot</code> puede incluir varios “temas” para el gráfico. En este caso se ha usado <code>theme_void()</code> que indica un fondo vacío. Finalmente, con la especificación <code>scale_fill_discrete(name=...)</code> se puede cambiar el título de la leyenda para que no aparezca el nombre de la variable, sino una etiqueta más adecuada.</p>
<pre class="r"><code>ggplot(data=df, aes(x=&quot;&quot;, y=per, fill=smedia1r))+
  geom_bar(width=1, stat=&quot;identity&quot;)+
  geom_text(aes(label=paste(per, &quot;%&quot;, sep=&quot;&quot;)), color=&quot;white&quot;, hjust=-0.3)+
  coord_polar(&quot;y&quot;, start=0)+
  theme_void()+
  scale_fill_discrete(name=&quot;¿Usa Facebook?&quot;)</code></pre>
<p><img src="Descriptivos_files/figure-html/ggpie2-1.png" width="672" /></p>
<p>Si en lugar de un gráfico circular se quiere presentar un gráfico de barras, con los datos del dataframe “lapop18” se puede utilizar el siguiente código. A diferencia del primer gráfico circular, ahora la especificación <code>aes(..)</code> incluye la variable “smedia1r” como variable a graficar en el eje X. Dentro del objeto geométrico <code>geom_bar()</code> se indica que la barra debe representar las proporciones en porcentajes <code>aes(y=..prop..*100, group=1)</code>. En este ejemplo, se ha incluido un etiqueta general para el gráfico y para los ejes con el comando <code>labs(...)</code>. En este comando también se puede agregar un “caption” para indicar la fuente de los datos. Finalmente, con la especificación <code>coord_cartesian(ylim=c(0,60))</code> se limita el eje Y a valores entre 0 y 60.</p>
<pre class="r"><code>ggplot(data=subset(lapop18, !is.na(smedia1r)), aes(x=smedia1r))+
  geom_bar(aes(y=..prop..*100, group=1), width=0.5)+
  labs(title=&quot;¿Qué tan frecuente se usan las redes sociales?&quot;, x=&quot;Usuario de Facebook&quot;, y=&quot;Porcentaje&quot;, caption=&quot;Barómetro de las Américas por LAPOP, 2018/19&quot;)+
  coord_cartesian(ylim=c(0, 60))</code></pre>
<p><img src="Descriptivos_files/figure-html/barras-1.png" width="672" /></p>
<p>En este caso tambien se puede usar los datos agrupados del dataframe “df”. A diferencia de la opción anterior, en “df” se cuenta con el dato del porcentaje, por lo que no se debe calcular en el código, por lo que en la especificación de la estética indica que en el eje X se bede mostrar las alternativas de la variable “smedia1r” y en el eje Y el porcentaje, de esta manera <code>aes(x=media1r, y=per)</code>. Por este motivo también en la especificación <code>geom_bar</code>, ahora en lugar de requerir el cálculo del porcentaje, solo se indica que replique los datos (con <code>stat="identity"</code>) de <code>aes</code>. Finalmente, en este caso le agregamos la capa de texto para incluir los porcentajes en cada columna, con la especificación <code>geom_text</code>.</p>
<pre class="r"><code>ggplot(df, aes(x=smedia1r, y=per))+
  geom_bar(stat=&quot;identity&quot;,  width=0.5)+
  geom_text(aes(label=paste(per, &quot;%&quot;, sep=&quot;&quot;)), color=&quot;black&quot;, vjust=-0.5)+
  labs(title=&quot;¿Qué tan frecuente se usan las redes sociales&quot;, x=&quot;Usuario de Facebook&quot;, y=&quot;Porcentaje&quot;, caption=&quot;Barómetro de las Américas por LAPOP, 2018/19&quot;)+
  coord_cartesian(ylim=c(0, 60))</code></pre>
<p><img src="Descriptivos_files/figure-html/tabla%20final-1.png" width="672" /></p>
</div>
<div id="resumen" class="section level1">
<h1>Resumen</h1>
<p>En este documento se ha trabajado con variables categóricas nominales, como si usa o no usa redes sociales. Se ha presentando las formas de cómo describir en tablas de frecuencia y cómo graficar estas variables, mediante gráficos circulares o de barras.</p>
</div>
<div id="nota-final" class="section level1">
<h1>Nota final</h1>
<p>En el reporte “El Pulso de la Democracia” no se reportan los datos de tenencia de cuentas de redes sociales (SMEDIA1, SMEDIA4 y SMEDIA7), sino las variables “usuarios de redes sociales”, que vimos cómo calcular. En todos estos cálculos no se ha tomado en cuenta el efecto de diseño, ni se ha incorporado el factor de expansión en los cálculos. Para comparar ambos resultados, sin y con la incorporación del efecto de diseño, se puede usar el comando <code>freq</code> sin y con la variable “weight1500”.</p>
<pre class="r"><code>freq(lapop18$smedia1r, plot = F)</code></pre>
<pre><code>## lapop18$smedia1r 
##       Frequency Percent Valid Percent
## Sí        15389  54.878         57.08
## No        11573  41.270         42.92
## NA&#39;s       1080   3.851              
## Total     28042 100.000        100.00</code></pre>
<pre class="r"><code>descr::freq(lapop18$smedia1r, lapop18$weight1500, plot = F)</code></pre>
<pre><code>## lapop18$smedia1r 
##       Frequency Percent Valid Percent
## Sí        14819  54.884         57.15
## No        11111  41.152         42.85
## NA&#39;s       1070   3.964              
## Total     27000 100.000        100.00</code></pre>
<p>Sin considerar el efecto de diseño, se tiene que 57.08% de entrevistados cuenta con una cuenta de Facebook. Este porcentaje varía a 57.15% si se incluye la variable de expansión. Estos resultados ponderados también se pueden guardar en objetos y luego graficar de la misma manera que se ha hecho con los resultados sin ponderar.</p>
</div>



</div>
</div>

</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open');
  });
});
</script>

<!-- code folding -->

<script>
$(document).ready(function ()  {

    // move toc-ignore selectors from section div to header
    $('div.section.toc-ignore')
        .removeClass('toc-ignore')
        .children('h1,h2,h3,h4,h5').addClass('toc-ignore');

    // establish options
    var options = {
      selectors: "h1",
      theme: "bootstrap3",
      context: '.toc-content',
      hashGenerator: function (text) {
        return text.replace(/[.\\/?&!#<>]/g, '').replace(/\s/g, '_');
      },
      ignoreSelector: ".toc-ignore",
      scrollTo: 0
    };
    options.showAndHide = true;
    options.smoothScroll = true;

    // tocify
    var toc = $("#TOC").tocify(options).data("toc-tocify");
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
