<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />




<title>Manejo de datos usando el Barómetro de las Américas</title>

<script src="site_libs/header-attrs-2.7/header-attrs.js"></script>
<script src="site_libs/jquery-1.11.3/jquery.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/bootstrap.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<style>h1 {font-size: 34px;}
       h1.title {font-size: 38px;}
       h2 {font-size: 30px;}
       h3 {font-size: 24px;}
       h4 {font-size: 18px;}
       h5 {font-size: 16px;}
       h6 {font-size: 12px;}
       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}
       pre:not([class]) { background-color: white }</style>
<script src="site_libs/jqueryui-1.11.4/jquery-ui.min.js"></script>
<link href="site_libs/tocify-1.9.1/jquery.tocify.css" rel="stylesheet" />
<script src="site_libs/tocify-1.9.1/jquery.tocify.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<link href="site_libs/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>

<style type="text/css">code{white-space: pre;}</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>








<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
pre code {
  padding: 0;
}
</style>


<style type="text/css">
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #adb5bd;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script type="text/javascript">
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark it active
  menuAnchor.tab('show');

  // if it's got a parent navbar menu mark it active as well
  menuAnchor.closest('li.dropdown').addClass('active');

  // Navbar adjustments
  var navHeight = $(".navbar").first().height() + 15;
  var style = document.createElement('style');
  var pt = "padding-top: " + navHeight + "px; ";
  var mt = "margin-top: -" + navHeight + "px; ";
  var css = "";
  // offset scroll position for anchor links (for fixed navbar)
  for (var i = 1; i <= 6; i++) {
    css += ".section h" + i + "{ " + pt + mt + "}\n";
  }
  style.innerHTML = "body {" + pt + "padding-bottom: 40px; }\n" + css;
  document.head.appendChild(style);
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "&#xe258;";
  border: none;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->



<style type="text/css">

#TOC {
  margin: 25px 0px 20px 0px;
}
@media (max-width: 768px) {
#TOC {
  position: relative;
  width: 100%;
}
}

@media print {
.toc-content {
  /* see https://github.com/w3c/csswg-drafts/issues/4434 */
  float: right;
}
}

.toc-content {
  padding-left: 30px;
  padding-right: 40px;
}

div.main-container {
  max-width: 1200px;
}

div.tocify {
  width: 20%;
  max-width: 260px;
  max-height: 85%;
}

@media (min-width: 768px) and (max-width: 991px) {
  div.tocify {
    width: 25%;
  }
}

@media (max-width: 767px) {
  div.tocify {
    width: 100%;
    max-width: none;
  }
}

.tocify ul, .tocify li {
  line-height: 20px;
}

.tocify-subheader .tocify-item {
  font-size: 0.90em;
}

.tocify .list-group-item {
  border-radius: 0px;
}


</style>



</head>

<body>


<div class="container-fluid main-container">


<!-- setup 3col/9col grid for toc_float and main content  -->
<div class="row">
<div class="col-sm-12 col-md-4 col-lg-3">
<div id="TOC" class="tocify">
</div>
</div>

<div class="toc-content col-sm-12 col-md-8 col-lg-9">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">LAPOP_edu</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="index.html">Home</a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Básico
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="instalando.html">Instalando R y RStudio</a>
    </li>
    <li>
      <a href="bases.html">Bases de datos</a>
    </li>
  </ul>
</li>
<li>
  <a href="Manipulacion.html">Manejo de datos</a>
</li>
<li>
  <a href="Expansion.html">Factor de expansión</a>
</li>
<li>
  <a href="Descriptivos.html">Descriptivos variables nominales</a>
</li>
<li>
  <a href="Descriptivos2.html">Descriptivos variables ordinales</a>
</li>
<li>
  <a href="Links.html">Contacto</a>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div id="header">



<h1 class="title toc-ignore">Manejo de datos usando el Barómetro de las Américas</h1>

</div>


<style type="text/css">
.columns {display: flex;}
h1 {color: #3366CC;}
</style>
<div id="introducción" class="section level1">
<h1>Introducción</h1>
<p>En este documento se verán aspectos básico del manejo de datos, como la recodificación de una variable, la selección de datos y el cálculo de una nueva variable.</p>
</div>
<div id="sobre-la-base-de-datos" class="section level1">
<h1>Sobre la base de datos</h1>
<p>Los datos que vamos a usar deben citarse de la siguiente manera: Fuente: Barómetro de las Américas por el Proyecto de Opinión Pública de América Latina (LAPOP), wwww.LapopSurveys.org. Pueden descargar los datos de manera libre <a href="http://datasets.americasbarometer.org/database/login.php">aquí</a> En este enlace, se pueden registrar o entrar como “Free User”. En el buscador, se puede ingresar el texto “2018”. Ahí se tendrá acceso a la base de datos completa “2018 LAPOP AmericasBarometer Merge_v1.0_W.dta en versión para STATA. Se descarga la base de datos en formato zip, la que se descomprime en formato .dta. Una vez descargada y guardada en el directorio de trabajo, se tiene que leer la base de datos como un objeto dataframe en R. En este documento se carga una base de datos recortada. Esta base de datos se encuentra alojada en el repositorio”materials_edu" de la cuenta de LAPOP en GitHub. Mediante la librería <code>rio</code> y el comando <code>import</code> se puede importar esta base de datos desde este repositorio, usando el siguiente código.</p>
<pre class="r"><code>library(rio)
lapop18 &lt;- import(&quot;https://raw.github.com/lapop-central/materials_edu/main/LAPOP_AB_Merge_2018_v1.0.sav&quot;)</code></pre>
</div>
<div id="recodificación-de-una-variable" class="section level1">
<h1>Recodificación de una variable</h1>
<p>El reporte “El Pulso de la Democracia” presenta los resultados acerca del apoyo a la democracia en las Américas. Estos resultados se basan en la variable ING4 de la base de datos. Esta variable está fraseada de la siguiente manera: ING4. Cambiando de nuevo de tema, puede que la democracia tenga problemas, pero es mejor que cualquier otra forma de gobierno. ¿Hasta qué punto está de acuerdo o en desacuerdo con esta frase? Como indica el reporte “los entrevistados evalúan esta frase dando una respuesta que va de 1 a 7, donde 1 significa”muy en desacuerdo" y 7 significa “muy de acuerdo” (p.11). Para ver la distribución de respuestas a esta variable, se puede usar el comando <code>table</code>.</p>
<pre class="r"><code>table(lapop18$ing4)</code></pre>
<pre><code>## 
##    1    2    3    4    5    6    7 
## 1699 1470 3003 6089 6530 4673 6625</code></pre>
<p>De esta manera se calculan las observaciones por cada valor de la variable. El reporte nos indica la forma de recodificación: “Se consideran las respuestas en la porción de la escala que indica estar de acuerdo, esto es los valores de 5 a 7, para indicar el porcentaje que apoya a la democracia” (p.11). Es decir, la variable original ING4, en una escala de 1-7, se tiene que recodificar en una nueva variable, siguiendo la siguiente regla:</p>
<ol style="list-style-type: decimal">
<li>Valores entre 1-4 de ING4 se transforman en 0 en la nueva variable ing4r</li>
<li>Valores entre 5-7 de ING4 se transformen en 1 en la nueva variable ing4r</li>
</ol>
<p>Para poder recodificar una variable hay varias formas. Una de las formas más eficientes de hacerlo es usando el comando <code>recode</code> del paquete <code>car</code>. El paquete <code>dplyr</code> tiene un comando <code>recode</code> que puede confundir a R. Para evitar confusiones usaremos la sintaxis <code>car::recode</code> para la recodificación y <code>table</code> para describir la nueva variable.</p>
<pre class="r"><code>lapop18$ing4rec &lt;- car::recode(lapop18$ing4, &quot;1:4=0; 5:7=1&quot;)
table(lapop18$ing4rec)</code></pre>
<pre><code>## 
##     0     1 
## 12261 17828</code></pre>
<p>Si se suman las observaciones entre 1 y 4 de la variable original (1699+1470+3003+6089), vemos que es el resultado que se tiene en el valor 0 de la nueva variable (12261), tal como se escribió en la recodificación.</p>
</div>
<div id="selección-de-casos" class="section level1">
<h1>Selección de casos</h1>
<p>El reporte indica que “El Gráfico 1.1 muestra el porcentaje de personas en cada país que expresa apoyar la democracia en 2018/19. El apoyo a la democracia va de un mínimo de 45% en Honduras a un máximo de 76.2% en Uruguay” (p.11). Para replicar estos resultados acerca de Honduras y acerca de Uruguay para 2018/19, se podría seleccionar los datos de estos dos países. De acuerdo al cuestionario, que se puede ver <a href="https://www.vanderbilt.edu/lapop/ab2018/AB2018-v12.0-Spa-190131_W.pdf">aquí</a>, Honduras es el país 4 y Uruguay es el país 14. La selección de casos en R se puede hacer de múltiples maneras. Una forma es usar [ ]. Otra forma es usando el comando <code>subset</code>. Entonces, seleccionamos las observaciones de estos países y guardamos esta selección en un nuevo dataframe “lapop2” usando este último comando (adicionalmente se incluye un comentario, que se marca con #, que incluye la sintaxis si se quisiera hacer con [ ]).</p>
<pre class="r"><code># lapop2 &lt;- lapop18[lapop18$pais == 4 | lapop18$pais==14, ]
lapop2 &lt;- subset(lapop18, pais==4 | pais==14)
table(lapop2$pais)</code></pre>
<pre><code>## 
##    4   14 
## 1560 1581</code></pre>
<p>Se ha descrito la variable “pais” para asegurarnos que el comando <code>subset</code> ha filtrado bien ambos países. Con esta selección de datos, se puede calcular los porcentajes reportados usando el comando <code>prop.table</code>. Este comando nos brinda las frecuencias relativas (en valores entre 0 y 1) de una tabla de frecuencias calculada con <code>table</code>. Estas frecuencias relativas se multiplican por 100 para reproducir el porcentaje en cada país. En este caso se usan los [ ] para hacer la selección de cada país.</p>
<pre class="r"><code>prop.table(table(lapop2$ing4rec[lapop2$pais==4]))*100</code></pre>
<pre><code>## 
##        0        1 
## 54.98995 45.01005</code></pre>
<pre class="r"><code>prop.table(table(lapop2$ing4rec[lapop2$pais==14]))*100</code></pre>
<pre><code>## 
##        0        1 
## 23.80641 76.19359</code></pre>
<p>Estos resultados son porcentajes (entre 0 y 100), pero incluye muchos decimales. Para redondear a un decimal, como se muestra en el Gráfico 1.2, se puede usar el comando <code>round</code> a toda la sintaxis anterior. En este comando, además, se tiene que especificar el número de decimales que se quiere, que en este caso es 1.</p>
<pre class="r"><code>round(prop.table(table(lapop2$ing4rec[lapop2$pais==4]))*100, 1)</code></pre>
<pre><code>## 
##  0  1 
## 55 45</code></pre>
<pre class="r"><code>round(prop.table(table(lapop2$ing4rec[lapop2$pais==14]))*100, 1)</code></pre>
<pre><code>## 
##    0    1 
## 23.8 76.2</code></pre>
<p>Con este código se ha reproducido los resultados de los países en los extremos del Gráfico 1.2 del reporte.</p>
<p>El reporte también indica que se excluye de los cálculos a Estados Unidos y Canadá. Es decir, en el dataframe “lapop18” se tiene que seleccionar los países que no son EE.UU. y Canadá. Esta nueva selección se puede guardar en un nuevo dataframe o se puede sobreescribir en el dataframe original, como se hace en este caso debido a que la exclusión de estos países es para todos los cálculos que siguen. De acuerdo al cuestionario, EE.UU. tiene el código 40 en la variable “pais” y Canadá, el código 41. Para excluirlos se tiene que incluir a los países que tengan un código menor a 40 (o de 35 o menos). Para esto nuevamente podemos usar el comando <code>subset</code>.</p>
<pre class="r"><code>lapop18 &lt;- subset(lapop18, pais&lt;=35)</code></pre>
<p>Se puede observar en el Environment que se reducen las observaciones del dataframe “lapop18” luego de correr este código, pues se han eliminado las observaciones de entrevistados en estos dos países.</p>
</div>
<div id="calcular-una-variable" class="section level1">
<h1>Calcular una variable</h1>
<p>Una práctica frecuente de LAPOP con los datos del Barómetro de las Américas es el re-escalamiento de variables. El capítulo sobre legitimidad democrática del reporte brinda ejemplos de este re-escalamiento con variables relacionadas al apoyo al sistema. Para calcular este índice de apoyo al sistema se trabaja con un conjunto de cinco variables:</p>
<p>B1. ¿Hasta qué punto cree usted que los tribunales de justicia de (país) garantizan un juicio justo? [Sondee: Si usted cree que los tribunales no garantizan para nada la justicia escoja el número 1; si cree que los tribunales garantizan mucho la justicia, escoja el número 7 o escoja un puntaje intermedio].</p>
<p>B2. ¿Hasta qué punto tiene usted respeto por las instituciones políticasl de (país)?</p>
<p>B3. ¿Hasta qué punto cree usted que los derechos básicos del ciudadano están bien protegidos por el sistema político de (país)?</p>
<p>B4. ¿Hasta qué punto se siente orgulloso de vivir bajo el sistema político de (país)?</p>
<p>B6. ¿Hasta qué punto piensa usted que se debe apoyar al sistema político de (país)?</p>
<p>Como indica el reporte “Para cada pregunta, la escala original de 1 (”Nada“) a 7 (”Mucho“) se recodifica en una escala de 0 a 100, de tal forma que 0 indica el menor nivel de apoyo al sistema político y 100 es el nivel máximo de apoyo al sistema político. Esta nueva escala sigue la recodificación típica de LAPOP y puede ser interpretada como una medición del apoyo en unidades, o grados, en una escala continua que va de 0 a 100” (p.34). Para comprobar la escala original de estas variables, se puede describir estas variables usando el comando <code>table</code>.</p>
<pre class="r"><code>table(lapop18$b1)</code></pre>
<pre><code>## 
##    1    2    3    4    5    6    7 
## 4089 4067 5881 6137 4215 1631 1371</code></pre>
<pre class="r"><code>table(lapop18$b2)</code></pre>
<pre><code>## 
##    1    2    3    4    5    6    7 
## 2861 2152 2998 4153 5182 4448 5679</code></pre>
<pre class="r"><code>table(lapop18$b3)</code></pre>
<pre><code>## 
##    1    2    3    4    5    6    7 
## 5080 4096 5153 5349 4219 2061 1491</code></pre>
<pre class="r"><code>table(lapop18$b4)</code></pre>
<pre><code>## 
##    1    2    3    4    5    6    7 
## 5095 3206 3743 4557 4326 3041 3584</code></pre>
<pre class="r"><code>table(lapop18$b6)</code></pre>
<pre><code>## 
##    1    2    3    4    5    6    7 
## 3713 2325 2971 4277 4616 3868 5572</code></pre>
<p>Se observa que efectivamente todas las variables corren en una escala de 1 a 7. Para reescalar una variable en una escala original de 1 a 7 a otra de 0 a 100, lo primero que se tiene que hacer es restar 1 unidad, con lo que la variable tendría una escala de 0 a 6, luego dividirla entre 6, con lo que variaría entre 0 y 1 y, finalmente, multiplicarla por 100. Esto es: Variable reescalada = ((variable original -1)/6)*100 El código para calcular esta nueva variable reescalada y para describir una de estas nuevas variables para comprobar el cambio es:</p>
<pre class="r"><code>lapop18$b1rec &lt;- ((lapop18$b1-1)/6)*100
lapop18$b2rec &lt;- ((lapop18$b2-1)/6)*100
lapop18$b3rec &lt;- ((lapop18$b3-1)/6)*100
lapop18$b4rec &lt;- ((lapop18$b4-1)/6)*100
lapop18$b6rec &lt;- ((lapop18$b6-1)/6)*100
table(lapop18$b1rec)</code></pre>
<pre><code>## 
##                0 16.6666666666667 33.3333333333333               50 
##             4089             4067             5881             6137 
## 66.6666666666667 83.3333333333333              100 
##             4215             1631             1371</code></pre>
<p>Con esta transformación se observa que los 4,089 entrevistados que marcaron 1 en la pregunta B1, ahora tienen un puntaje de 0. Los 4,067 que marcaron 2, ahora tienen un puntaje de 16.67, es decir 2-1=1/6=0.1667*100=16.67. Esta misma operación se pudo hacer con el comando <code>car::recode</code>, siguiendo la siguiente regla de recodificación:</p>
<ul>
<li>Valor de 1 en variable original se recodifica como 0 en nueva variable</li>
<li>Valor de 2 en variable original se recodifica como 16.67 en nueva variable</li>
<li>Valor de 3 en variable original se recodifica como 33.33 en nueva variable</li>
<li>Valor de 4 en variable original se recodifica como 50 en nueva variable</li>
<li>Valor de 5 en variable original se recodifica como 66.67 en nueva variable</li>
<li>Valor de 6 en variable original se recodifica como 83.33 en nueva variable</li>
<li>Valor de 7 en variable original se recodifica como 100 en nueva variable</li>
</ul>
<p>Esta manera de recodificar, sin embargo, es poco eficiente. Es más simple usar la fórmula para calcular la recodificación. Para calcular el índice de apoyo al sistema, el reporte indica que “El índice de apoyo al sistema es el promedio de cinco preguntas: B1, B2, B3, B4 y B6” (p.46). Es decir, con las variables reescaladas se tiene que calcular el promedio de estas cinco variables para cada individuo (es decir, en cada fila de la base de datos). Esta operación se podría realizar calculando el promedio de forma manual. Apoyo al sistema = (b1rec + b2rec + b3rec + b4rec + b6rec)/5 En R tenemos el comando <code>rowMeans</code> que sirva para calcular promedios de ciertas columnas por cada fila. La sintaxis <code>[, 86:90]</code> indica que se realizará el cálculo del promedio por filas para todas las filas y usando las columnas 86 a 90 del dataframe “lapop18” (se podría hacer el cálculo para algunas filas en particular definiendo <code>[fila_n:fila_m, 86:90]</code>). Este promedio se guarda en una nueva variable “apoyo”, que se describe.</p>
<pre class="r"><code>lapop18$apoyo &lt;- rowMeans(lapop18[,86:90])
table(lapop18$apoyo)</code></pre>
<pre><code>## 
##                0 3.33333333333333 6.66666666666667               10 
##              634              368              439              525 
## 13.3333333333333 16.6666666666667               20 23.3333333333333 
##              527              550              834              745 
## 26.6666666666667               30 33.3333333333333 36.6666666666667 
##              810              911             1063             1086 
##               40 43.3333333333333 46.6666666666667               50 
##             1287             1317             1254             1487 
## 53.3333333333333 56.6666666666667               60 63.3333333333333 
##             1397             1408             1449             1243 
## 66.6666666666667               70 73.3333333333333 76.6666666666667 
##             1227             1113              988              827 
##               80 83.3333333333333 86.6666666666667               90 
##              820              572              445              369 
## 93.3333333333333 96.6666666666667              100 
##              245              131              210</code></pre>
<p>Con este índice se puede calcular el apoyo al sistema promedio para la última ronda del Barómetro de las Américas, así como los promedios de cada una de las variables que componen el índice. Se usa el comando <code>mean</code> para el promedio y la especificación <code>na.rm=T</code> para indicarle al comando que no tome en cuenta los valores perdidos de estas variables. Estos estadísticos se verán en más detalle en otros documentos.</p>
<pre class="r"><code>mean(lapop18$apoyo, na.rm=T)</code></pre>
<pre><code>## [1] 48.79419</code></pre>
<pre class="r"><code>mean(lapop18$b1rec, na.rm=T)</code></pre>
<pre><code>## [1] 41.06032</code></pre>
<pre class="r"><code>mean(lapop18$b2rec, na.rm=T)</code></pre>
<pre><code>## [1] 59.23937</code></pre>
<pre class="r"><code>mean(lapop18$b3rec, na.rm=T)</code></pre>
<pre><code>## [1] 40.42406</code></pre>
<pre class="r"><code>mean(lapop18$b4rec, na.rm=T)</code></pre>
<pre><code>## [1] 47.41096</code></pre>
<pre class="r"><code>mean(lapop18$b6rec, na.rm=T)</code></pre>
<pre><code>## [1] 56.28337</code></pre>
</div>
<div id="calcular-una-variable-de-manera-condicional" class="section level1">
<h1>Calcular una variable de manera condicional</h1>
<p>En algunas ocasiones el cálculo de una variable no requiere solamente la transformación numérica de la variable original, sino que los valores de la nueva variable dependen de valores de otras variables. Por ejemplo, el capítulo “Redes sociales y actitudes políticas” del reporte “El Pulso de la Democracia” presenta los resultados para las variables “usuario de Whatsapp”, “usuario de Twitter” y “usuario de Facebook”. Para calcular estas variables, el pie de página 7 de este capítulo indica: “Para cada plataforma, se identifican los usuarios con una combinación de dos conjuntos de preguntas. Primero, se identifican como usuarios a quienes responden positivamente a las preguntas, SMEDIA1/SMEDIA4/SMEDIA7. ¿Tiene usted cuenta de Facebook/Twitter/Whatsapp? Luego, se recodifica como no usuario a quienes responden”nunca" a las preguntas siguientes, SMEDIA2/SMEDIA5/SMEDIA8. ¿Con qué frecuencia ve contenido en Facebook/Twitter/Whatsapp?“. Es decir, el usuario no solo es el que tiene una cuenta, sino el que la usa con cierta frecuencia. De esta manera, el no usuario puede tener una cuenta, pero nunca usarla. Por lo tanto, la variable”usuario" depende de los valores de 2 variables. La regla de codificación que se sigue es:</p>
<ul>
<li><p>Usuario de Facebook = 1 (sí es usuario) si SMEDIA1 = 1 (tiene cuenta) y SMEDIA2 &lt;= 4 (la usa con alguna frecuencia)</p></li>
<li><p>Usuario de Facebook = 0 (no es usuario) si SMEDIA2 = 2 (no tiene cuenta) o SMEDIA2 = 5 (tiene cuenta pero nunca la usa)</p></li>
</ul>
<p>Esta regla se transforma en la siguiente sintaxis de R, que usa el comando <code>ìfelse</code>. Esta sintaxis incluye la condición para asignar valores de 1 a una nueva variable y asigna a todas las demás observaciones el valor de 0. Se describen estas nuevas variables usando los comandos <code>table</code> para generar las frecuencias absolutas, <code>prop.table</code> para las frecuencias relativas y <code>round</code> para redondear los decimales. Estos comandos se verán en más detalle en los siguientes documentos.</p>
<pre class="r"><code>lapop18$fb_user &lt;- ifelse(lapop18$smedia1==1 &amp; lapop18$smedia2&lt;=4, 1, 0)
lapop18$tw_user &lt;- ifelse(lapop18$smedia4==1 &amp; lapop18$smedia5&lt;=4, 1, 0)
lapop18$wa_user &lt;- ifelse(lapop18$smedia7==1 &amp; lapop18$smedia8&lt;=4, 1, 0)
round(prop.table(table(lapop18$fb_user))*100, 1)</code></pre>
<pre><code>## 
##    0    1 
## 43.8 56.2</code></pre>
<pre class="r"><code>round(prop.table(table(lapop18$tw_user))*100, 1)</code></pre>
<pre><code>## 
##    0    1 
## 92.1  7.9</code></pre>
<pre class="r"><code>round(prop.table(table(lapop18$wa_user))*100, 1)</code></pre>
<pre><code>## 
##    0    1 
## 35.8 64.2</code></pre>
</div>
<div id="observación-del-efecto-de-diseño" class="section level1">
<h1>Observación del efecto de diseño</h1>
<p>Tanto los resultados para apoyo al sistema, como los de usuarios de redes sociales difieren de los que aparecen en el reporte por dos motivos. En primer lugar, para apoyo al sistema, debido a que “Los valores a lo largo del tiempo se calculan incluyendo únicamente los países que el Barómetro de las Américas ha estudiado regularmente desde 2006: Argentina, Brasil, Bolivia, Chile, Colombia, Costa Rica, República Dominicana, Ecuador, El Salvador, Guatemala, Honduras, Jamaica, México, Nicaragua, Panamá, Paraguay, Perú, Uruguay” (p.46). El código solo filtra la última ronda, que incluye países que no están en esa lista, como Estados Unidos o Canadá. De otro lado, los cálculos reportados en la publicación incluyen el uso de factores de expansión, que no se han incluido en estos cálculos, pero que en otros documentos se incorporarán (ver <a href="https://rpubs.com/arturo_maldonado/728626">aquí</a>).</p>
</div>
<div id="resumen" class="section level1">
<h1>Resumen</h1>
<p>En este documento se han visto los elementos básicos de la manipulación y transformación de datos usando el Barómetro de las Américas. Se ha recodificado una variable usando el comando <code>recode</code>, se ha seleccionado casos usando <code>subset</code> y se ha calculado una nueva variable algebraicamente y con el comando <code>ìfelse</code>.</p>
</div>



</div>
</div>

</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open');
  });
});
</script>

<!-- code folding -->

<script>
$(document).ready(function ()  {

    // move toc-ignore selectors from section div to header
    $('div.section.toc-ignore')
        .removeClass('toc-ignore')
        .children('h1,h2,h3,h4,h5').addClass('toc-ignore');

    // establish options
    var options = {
      selectors: "h1",
      theme: "bootstrap3",
      context: '.toc-content',
      hashGenerator: function (text) {
        return text.replace(/[.\\/?&!#<>]/g, '').replace(/\s/g, '_');
      },
      ignoreSelector: ".toc-ignore",
      scrollTo: 0
    };
    options.showAndHide = true;
    options.smoothScroll = true;

    // tocify
    var toc = $("#TOC").tocify(options).data("toc-tocify");
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
